# Generated by Django 2.2.19 on 2021-04-24 08:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('5462e697-d5e7-47fb-b6a9-7aad6a9d9121'), editable=False, primary_key=True, serialize=False, verbose_name='идентификатор')),
                ('title', models.CharField(max_length=100, verbose_name='наименование')),
                ('slug', models.SlugField()),
                ('description', models.TextField(verbose_name='описание')),
                ('start_date', models.DateField(verbose_name='дата начала действия')),
                ('version', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='код')),
                ('value', models.CharField(max_length=200, verbose_name='значение')),
                ('guide', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elements', to='api.Guide')),
            ],
            options={
                'ordering': ('code',),
            },
        ),
    ]
