# Generated by Django 2.2.19 on 2021-04-26 17:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='идентификатор')),
                ('title', models.CharField(max_length=100, verbose_name='наименование')),
                ('slug', models.SlugField(verbose_name='короткое наименование')),
                ('description', models.TextField(verbose_name='описание')),
                ('start_date', models.DateField(verbose_name='дата начала действия')),
                ('version', models.CharField(max_length=5)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='GuideVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, verbose_name='версия справочника')),
                ('guide_unique', models.CharField(max_length=64, verbose_name='идентификатор справочника')),
                ('date_from', models.DateField(verbose_name='дата начала действия')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='api.Guide', verbose_name='наименование справочника')),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='код')),
                ('value', models.CharField(max_length=200, verbose_name='значение')),
                ('guide', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elements', to='api.Guide')),
            ],
            options={
                'ordering': ('code',),
            },
        ),
    ]
