# Generated by Django 2.2.19 on 2021-04-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='version',
            field=models.ManyToManyField(blank=True, help_text='(Выберите версии справочников для элемента.', related_name='elements', to='api.GuideVersion', verbose_name='версия справочника'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='title',
            field=models.CharField(max_length=100, verbose_name='наименование справочника'),
        ),
        migrations.AlterField(
            model_name='guideversion',
            name='guide_unique',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='идентификатор справочника'),
        ),
    ]
