# Generated by Django 2.2.19 on 2021-04-25 02:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='id',
            field=models.UUIDField(default=uuid.UUID('89f651a3-132a-424d-a1f1-facaa85a9151'), editable=False, primary_key=True, serialize=False, verbose_name='идентификатор'),
        ),
    ]
