# Generated by Django 2.2.19 on 2021-04-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210428_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='version',
            field=models.ManyToManyField(blank=True, help_text='Выберите версии справочников для элемента.', related_name='elements', to='api.GuideVersion', verbose_name='версия справочника'),
        ),
    ]
