# Generated by Django 2.2.19 on 2021-04-25 03:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210425_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='id',
            field=models.UUIDField(default=uuid.UUID('29511706-d489-4203-83a2-c8f033f070fb'), editable=False, primary_key=True, serialize=False, verbose_name='идентификатор'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
