# Generated by Django 2.2.19 on 2021-04-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210428_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='slug',
            field=models.SlugField(max_length=30, verbose_name='короткое наименование'),
        ),
    ]
