# Generated by Django 2.2.19 on 2021-04-25 03:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210425_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0ba6b856-2e73-410f-a25d-726c7a17e1cb'), editable=False, primary_key=True, serialize=False, verbose_name='идентификатор'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='slug',
            field=models.SlugField(),
        ),
    ]
