# Generated by Django 2.2.19 on 2021-04-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210428_2239'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='guideversion',
            name='unique guideversion',
        ),
        migrations.AlterField(
            model_name='guide',
            name='slug',
            field=models.SlugField(max_length=30, unique=True, verbose_name='короткое наименование'),
        ),
        migrations.AddConstraint(
            model_name='guideversion',
            constraint=models.UniqueConstraint(fields=('guide_unique', 'name'), name='unique_guideversion'),
        ),
    ]
