# Generated by Django 2.2.19 on 2021-04-25 13:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210425_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7bb88481-521b-4466-a1fa-9868062f6b48'), editable=False, primary_key=True, serialize=False, verbose_name='идентификатор'),
        ),
    ]
