# Generated by Django 2.2.19 on 2021-04-25 14:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210425_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6d35a201-cc1b-4e0c-b605-d3b3b15d88f4'), primary_key=True, serialize=False, verbose_name='идентификатор'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='slug',
            field=models.SlugField(verbose_name='короткое наименование'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='version',
            field=models.CharField(max_length=5),
        ),
        migrations.CreateModel(
            name='GuideVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='версия справочника')),
                ('date_from', models.DateField()),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='api.Guide')),
            ],
            options={
                'unique_together': {('number', 'guide')},
            },
        ),
    ]
