# Generated by Django 3.2 on 2021-05-13 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210512_2108'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='guideversion',
            name='unique_guide_version',
        ),
    ]
