# Generated by Django 3.2 on 2021-05-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_guideversion_unique_guide_version'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='guideversion',
            constraint=models.UniqueConstraint(fields=('guide_unique', 'name'), name='unique_guide_version'),
        ),
    ]
